---
# etcd role defaults

etcd_version: "3.5.21"
etcd_package_repo: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
etcd_conf_dir: "/etc/etcd"
etcd_data_dir: "/var/lib/etcd"
etcd_cluster_name: "etcd-cluster"
patroni_etcd_protocol: "http"
installation_method: "packages"
