apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-db-secret
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}

